name: odyssey-testnet
services:
  db:
    environment:
      POSTGRES_PASSWORD: momentum
      POSTGRES_USER: momentum
      POSTGRES_DB: momentum
      PGUSER: momentum
#    volumes:
#      - ./postgresql/database-schema.sql:/docker-entrypoint-initdb.d/00-init-schema.sql:ro
#      - ./postgresql/database-data.sql.xz:/docker-entrypoint-initdb.d/01-init-data.sql.xz:ro
    ports:
      - "54321:5432"

  controller:
    ports:
      - "4001:4000"
    env_file:
      - ./goerli-testnet.env
    environment:
      DB_USERNAME: "momentum"
      DB_PASSWORD: "momentum"
      DB_DATABASE: "momentum"
      DB_MAX_CONNS: "4"
      CONTROLLER_LOGLEVEL: "0"
      FRONTEND_URL: http://localhost:8081

  frontend:
    ports:
      - "8081:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

