# TODO: actually implement this
services:
  influx:
    image: influxdb2:2.0.6-alpine
    pull_policy: missing
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=influx
      - DOCKER_INFLUXDB_INIT_PASSWORD=pw
      - DOCKER_INFLUXDB_INIT_ORG=momentum
      - DOCKER_INFLUXDB_INIT_BUCKET=momentum
    volumes:
      - influx-data:/var/lib/influxdb2
    profiles:
      - influx

volumes:
  influx-data:
